data:
  batch_size: 64
  data_dir: data/VN-celeb
  name: Our
  num_workers: 4
device: cuda
model:
  attn_p: 0.0
  depth: 12
  embedding_dim: 512
  img_size: 72
  in_channels: 3
  mlp_ratio: 4.0
  n_heads: 4
  num_classes: 2
  p: 0.0
  patch_size: 24
  qkv_bias: true
stage: pretrain
train:
  epochs: 25
  log_interval: 10
  lr: 0.0003
  save_dir: checkpoints/pretrain
  weight_decay: 1.0e-05
